name: Tan Thai Group
favicon: null
layout_spectrum: 0.99216
typography_spectrum: 0.021939935628324747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ec6821'
    - '#f6f6f6'
    - '#7b7b7b'
    - '#ff0000'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
